#!/bin/bash

# Gradle wrapper script for Unix/Linux/macOS
# This is a placeholder - the actual gradlew script should be generated by gradle init

echo "Please run 'gradle wrapper' from a machine with Gradle installed to generate this file."
echo "Or download it from: https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/resources/gradlew"
